apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      nodePort: 30002
      targetPort: 8081
      protocol: TCP
  selector:
    app: frontend