apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      nodePort: 30001
      targetPort: 5000
      protocol: TCP
  selector:
    app: backend